#!/bin/bash

# save command line arguments
data_file=$1
cell_id=$2
cell_description=$3

if [[ -n REPRO_DEMO_TMP_DIRNAME ]] ; then
    tmp_dir=${REPRO_DEMO_TMP_DIRNAME}
    mkdir -p ${tmp_dir}
else
    tmp_dir=$(mktemp --tmpdir=/tmp -d bash_dev_XXXXXXX)
fi

# define names of query and query result files
cell_code=${REPRO_DEMO_TMP_DIRNAME}/${cell_id}.rq
cell_output=${REPRO_DEMO_TMP_DIRNAME}/${cell_id}.txt

# copy stdin to the cell code file
cat /dev/null > ${cell_code}
IFS=''; while read line
do
    printf "$line\n" >> ${cell_code}
done

# execute the query on the given data file and save results
java -cp "${JENA_CLASSPATH}" arq.sparql --syntax arq --data ${data_file} --query ${cell_code} > ${cell_output}

# print the query results
echo "============================================ ARQ CELL ${cell_id} =============================================="
cat ${cell_code}
echo "--------------------------------------------- OUTPUTS -------------------------------------------------"
cat ${cell_output}
echo "-------------------------------------------------------------------------------------------------------"
echo
echo
